name: Test

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup swiftly
        run: |
          curl -O 'https://download.swift.org/swiftly/darwin/swiftly.pkg'
          installer -pkg swiftly.pkg -target CurrentUserHomeDirectory
          SWIFTLY_BIN_PATH="${HOME}/.swiftly/bin/swiftly"
          SWIFTLY_ENV_PATH="${HOME}/.swiftly/env.sh"

          "${SWIFTLY_BIN_PATH}" init --assume-yes --no-modify-profile --skip-install --quiet-shell-followup
          . "${SWIFTLY_ENV_PATH}"
          echo "SWIFTLY_HOME_DIR=${SWIFTLY_HOME_DIR}" >>"${GITHUB_ENV}"
          echo "SWIFTLY_BIN_DIR=${SWIFTLY_BIN_DIR}" >>"${GITHUB_ENV}"
          echo "${SWIFTLY_BIN_DIR}" >>"${GITHUB_PATH}"

      - name: Install Swift 6.2
        run: |
          POST_INSTALL_FILE="${HOME}/.swiftly-postinstall-cmds.sh"
          swiftly install --assume-yes --use --post-install-file "${POST_INSTALL_FILE}" "6.2"
          if [[ -f "${POST_INSTALL_FILE}" ]]; then
            export DEBIAN_FRONTEND=noninteractive # prevent Debian/Ubuntu installs from hanging on tzdata
            if [[ "$(id -un)" == 'root' ]]; then
              . "${POST_INSTALL_FILE}"
            else
              sudo bash -c ". '${POST_INSTALL_FILE}'"
            fi
            rm "${POST_INSTALL_FILE}"
          fi

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v
